In [1]:
import pandas as pd
import numpy as np
from datetime import date, timedelta

In [2]:
adnimerge = pd.read_csv('ADNIMERGE.csv')
current_sheet = pd.read_excel('fMRI_Scan_Visits_ADNI.xlsx')
current_sheet = current_sheet.drop([0],axis=0)#0th row is all nans

/home/yadnesh/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (18,19,20,103,104) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
adnimerge.head()

RID        PTID VISCODE  SITE COLPROT ORIGPROT    EXAMDATE DX_bl   AGE  \
0    2  011_S_0002      bl    11   ADNI1    ADNI1  2005-09-08    CN  74.3   
1    3  011_S_0003      bl    11   ADNI1    ADNI1  2005-09-12    AD  81.3   
2    3  011_S_0003     m06    11   ADNI1    ADNI1  2006-03-13    AD  81.3   
3    3  011_S_0003     m12    11   ADNI1    ADNI1  2006-09-12    AD  81.3   
4    3  011_S_0003     m24    11   ADNI1    ADNI1  2007-09-12    AD  81.3   

  PTGENDER  ...  TAU_bl PTAU_bl   FDG_bl PIB_bl  AV45_bl  Years_bl  Month_bl  \
0     Male  ...     NaN     NaN  1.36665    NaN      NaN  0.000000   0.00000   
1     Male  ...   239.7   22.83  1.08355    NaN      NaN  0.000000   0.00000   
2     Male  ...   239.7   22.83  1.08355    NaN      NaN  0.498289   5.96721   
3     Male  ...   239.7   22.83  1.08355    NaN      NaN  0.999316  11.96720   
4     Male  ...   239.7   22.83  1.08355    NaN      NaN  1.998630  23.93440   

   Month     M           update_stamp  
0      0   0.0  2020-01-09 04:20:17.0  
1      0   0.0  2020-01-09 04:20:17.0  
2      6   6.0  2020-03-25 15:43:58.0  
3     12  12.0  2020-01-09 04:20:17.0  
4     24  24.0  2020-01-09 04:20:17.0  

[5 rows x 113 columns]

In [4]:
current_sheet.head()

Subject ID  Sex  Weight  Research Group                        Visit   \
1  021_S_6312   M      81.7             CN           ADNI3 Year 1 Visit    
2  301_S_6326   M      73.0             CN               ADNI Screening    
3  301_S_6326   M      68.0             CN           ADNI3 Year 1 Visit    
4  002_S_4473   M      77.0           EMCI   ADNI2 Screening MRI-New Pt    
5  002_S_4473   M      75.0           EMCI     ADNI2 Month 3 MRI-New Pt    

  Study Date   Age                Description   \
1  4/30/2019   81.3  Axial rsfMRI (Eyes Open)    
2  4/26/2018   75.8   Axial fcMRI (EYES OPEN)    
3   6/6/2019   76.9   Axial fcMRI (EYES OPEN)    
4  2/10/2012   74.9        Resting State fMRI    
5  5/17/2012   75.2        Resting State fMRI    

                                   Imaging Protocol   \
1  Manufacturer=GE MEDICAL SYSTEMS;Field Strength...   
2  Manufacturer=Philips Medical Systems;Field Str...   
3  Manufacturer=Philips Medical Systems;Field Str...   
4  Manufacturer=Philips Medical Systems;Field Str...   
5  Manufacturer=Philips Medical Systems;Field Str...   

  Cohort Assigned (by script) ADAS 11 ADAS 13 MMSE CDR_SB RAVLT_immediate  \
1                     MCI_NC       10      16   26      0              29   
2                     MCI_NC       10      15   29      0              32   
3                     MCI_NC       []      []   []     []              []   
4                     MCI_NC      NaN     NaN  NaN    NaN             NaN   
5                     MCI_NC        6       9   29      2              42   

  RAVLT_learning RAVLT_forget LDEL_Total Digit_SCore ECog_Pt_Total  
1              0            6         12         NaN       1.37838  
2              5            5          9         NaN       1.18421  
3             []           []         []          []            []  
4            NaN          NaN        NaN         NaN           NaN  
5              6            2        NaN         NaN             2

In [5]:
print(list(adnimerge.columns))

['RID', 'PTID', 'VISCODE', 'SITE', 'COLPROT', 'ORIGPROT', 'EXAMDATE', 'DX_bl', 'AGE', 'PTGENDER', 'PTEDUCAT', 'PTETHCAT', 'PTRACCAT', 'PTMARRY', 'APOE4', 'FDG', 'PIB', 'AV45', 'ABETA', 'TAU', 'PTAU', 'CDRSB', 'ADAS11', 'ADAS13', 'ADASQ4', 'MMSE', 'RAVLT_immediate', 'RAVLT_learning', 'RAVLT_forgetting', 'RAVLT_perc_forgetting', 'LDELTOTAL', 'DIGITSCOR', 'TRABSCOR', 'FAQ', 'MOCA', 'EcogPtMem', 'EcogPtLang', 'EcogPtVisspat', 'EcogPtPlan', 'EcogPtOrgan', 'EcogPtDivatt', 'EcogPtTotal', 'EcogSPMem', 'EcogSPLang', 'EcogSPVisspat', 'EcogSPPlan', 'EcogSPOrgan', 'EcogSPDivatt', 'EcogSPTotal', 'FLDSTRENG', 'FSVERSION', 'IMAGEUID', 'Ventricles', 'Hippocampus', 'WholeBrain', 'Entorhinal', 'Fusiform', 'MidTemp', 'ICV', 'DX', 'mPACCdigit', 'mPACCtrailsB', 'EXAMDATE_bl', 'CDRSB_bl', 'ADAS11_bl', 'ADAS13_bl', 'ADASQ4_bl', 'MMSE_bl', 'RAVLT_immediate_bl', 'RAVLT_learning_bl', 'RAVLT_forgetting_bl', 'RAVLT_perc_forgetting_bl', 'LDELTOTAL_BL', 'DIGITSCOR_bl', 'TRABSCOR_bl', 'FAQ_bl', 'mPACCdigit_bl', 'mPA

In [6]:
print(list(current_sheet.columns))

['Subject ID\xa0', 'Sex', 'Weight\xa0', 'Research Group\xa0', 'Visit\xa0', 'Study Date\xa0', 'Age\xa0', 'Description\xa0', 'Imaging Protocol\xa0', 'Cohort Assigned (by script)', 'ADAS 11', 'ADAS 13', 'MMSE', 'CDR_SB', 'RAVLT_immediate', 'RAVLT_learning', 'RAVLT_forget', 'LDEL_Total', 'Digit_SCore', 'ECog_Pt_Total']


In [7]:
#taking subset of columns which are required
adnimerge_req_df = adnimerge[['PTID','EXAMDATE','APOE4','ADAS11','ADAS13','MMSE','CDRSB','RAVLT_immediate',
                              'RAVLT_learning','RAVLT_forgetting','LDELTOTAL','DIGITSCOR','EcogPtTotal']]
adnimerge_req_df.head()

PTID    EXAMDATE  APOE4  ADAS11  ADAS13  MMSE  CDRSB  \
0  011_S_0002  2005-09-08    0.0   10.67   18.67  28.0    0.0   
1  011_S_0003  2005-09-12    1.0   22.00   31.00  20.0    4.5   
2  011_S_0003  2006-03-13    1.0   19.00   30.00  24.0    6.0   
3  011_S_0003  2006-09-12    1.0   24.00   35.00  17.0    3.5   
4  011_S_0003  2007-09-12    1.0   25.67   37.67  19.0    8.0   

   RAVLT_immediate  RAVLT_learning  RAVLT_forgetting  LDELTOTAL  DIGITSCOR  \
0             44.0             4.0               6.0       10.0       34.0   
1             22.0             1.0               4.0        2.0       25.0   
2             19.0             2.0               6.0        NaN       19.0   
3             31.0             2.0               7.0        0.0       21.0   
4             23.0             1.0               5.0        0.0       16.0   

   EcogPtTotal  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

### Removing white spaces from values and converting to date-time

In [8]:
subject_id_list = [i.strip() for i in list(current_sheet['Subject ID\xa0'])]
subject_scan_date = [i.strip()  for i in list(current_sheet['Study Date\xa0'])]
current_sheet['Subject ID\xa0'] = subject_id_list
current_sheet['Study Date\xa0'] = subject_scan_date

current_sheet['Study Date\xa0'] =  pd.to_datetime(current_sheet['Study Date\xa0'], format='%m/%d/%Y')
adnimerge_req_df['EXAMDATE'] = pd.to_datetime(adnimerge_req_df['EXAMDATE'], format='%Y-%m-%d')

/home/yadnesh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [9]:
subject_id_list = list(current_sheet['Subject ID\xa0'])
subject_scan_date = list(current_sheet['Study Date\xa0'])
print(subject_id_list[1],subject_scan_date[1])

301_S_6326 2018-04-26 00:00:00


In [13]:
def closest_date(scan_date,list_dates):
    diff=timedelta(100000)#approx 273 years
    index_closest_date = 0
    for i in range(len(list_dates)):
        if abs(scan_date-list_dates[i])<diff:
            diff = abs(scan_date-list_dates[i])
            index_closest_date = i
    return list_dates[index_closest_date]

## Trail run for 10 rows

In [12]:
revised_scores = []

assert (len(subject_id_list)==len(subject_scan_date))

for i in range(len(subject_scan_date[:10])):
    exam_df = adnimerge_req_df[(adnimerge_req_df['PTID'] == subject_id_list[i])&
                               (adnimerge_req_df['EXAMDATE']>subject_scan_date[i]-timedelta(days=150))&
                               (adnimerge_req_df['EXAMDATE']<subject_scan_date[i]+timedelta(days=150))]
    print(subject_scan_date[i])
    print(exam_df)
    print(exam_df.shape)
    if exam_df.shape[0]>1:
        print("*******************************")
        exam_dates_in_range = list(exam_df['EXAMDATE'])
        nearest_date = closest_date(subject_scan_date[i],exam_dates_in_range)
        print("closest date = ",nearest_date)
        final_exam_df = exam_df[exam_df['EXAMDATE']==nearest_date]
        print("*******************************")
        print(final_exam_df)
        print("*******************************")
        assert (final_exam_df.shape[0]==1)
        for index, rows in final_exam_df.iterrows():
            revised_scores.append([rows.EXAMDATE, rows.APOE4, rows.ADAS11, rows.ADAS13, rows.MMSE, rows.CDRSB,
                                   rows.RAVLT_immediate, rows.RAVLT_learning,rows.RAVLT_forgetting,
                                   rows.LDELTOTAL, rows.DIGITSCOR, rows.EcogPtTotal])
    elif exam_df.shape[0]==1:
        for index, rows in exam_df.iterrows():
            revised_scores.append([rows.EXAMDATE, rows.APOE4, rows.ADAS11, rows.ADAS13, rows.MMSE, rows.CDRSB,
                                   rows.RAVLT_immediate, rows.RAVLT_learning,rows.RAVLT_forgetting,
                                   rows.LDELTOTAL, rows.DIGITSCOR, rows.EcogPtTotal])
    else:
        revised_scores.append(['Not found']*12)

print(len(revised_scores))
print(revised_scores)

2019-04-30 00:00:00
             PTID   EXAMDATE  APOE4  ADAS11  ADAS13  MMSE  CDRSB  \
13939  021_S_6312 2019-04-30    1.0    10.0    16.0  26.0    0.0   

       RAVLT_immediate  RAVLT_learning  RAVLT_forgetting  LDELTOTAL  \
13939             29.0             0.0               6.0       12.0   

       DIGITSCOR  EcogPtTotal  
13939        NaN      1.37838  
(1, 13)
2018-04-26 00:00:00
             PTID   EXAMDATE  APOE4  ADAS11  ADAS13  MMSE  CDRSB  \
13329  301_S_6326 2018-06-04    0.0    10.0    15.0  29.0    0.0   

       RAVLT_immediate  RAVLT_learning  RAVLT_forgetting  LDELTOTAL  \
13329             32.0             5.0               5.0        9.0   

       DIGITSCOR  EcogPtTotal  
13329        NaN      1.18421  
(1, 13)
2019-06-06 00:00:00
             PTID   EXAMDATE  APOE4  ADAS11  ADAS13  MMSE  CDRSB  \
14254  301_S_6326 2019-06-05    0.0    9.67   13.67  29.0    1.0   

       RAVLT_immediate  RAVLT_learning  RAVLT_forgetting  LDELTOTAL  \
14254             38.0      

## Running on all rows

In [14]:
revised_scores = []

assert (len(subject_id_list)==len(subject_scan_date))

for i in range(len(subject_scan_date)):
    exam_df = adnimerge_req_df[(adnimerge_req_df['PTID'] == subject_id_list[i])&
                               (adnimerge_req_df['EXAMDATE']>subject_scan_date[i]-timedelta(days=150))&
                               (adnimerge_req_df['EXAMDATE']<subject_scan_date[i]+timedelta(days=150))]
    
    if exam_df.shape[0]>1:
        exam_dates_in_range = list(exam_df['EXAMDATE'])
        nearest_date = closest_date(subject_scan_date[i],exam_dates_in_range)
        final_exam_df = exam_df[exam_df['EXAMDATE']==nearest_date]
        
        assert (final_exam_df.shape[0]==1)
        for index, rows in final_exam_df.iterrows():
            revised_scores.append([rows.EXAMDATE, rows.APOE4, rows.ADAS11, rows.ADAS13, rows.MMSE, rows.CDRSB,
                                   rows.RAVLT_immediate, rows.RAVLT_learning,rows.RAVLT_forgetting,
                                   rows.LDELTOTAL, rows.DIGITSCOR, rows.EcogPtTotal])
    elif exam_df.shape[0]==1:
        for index, rows in exam_df.iterrows():
            revised_scores.append([rows.EXAMDATE, rows.APOE4, rows.ADAS11, rows.ADAS13, rows.MMSE, rows.CDRSB,
                                   rows.RAVLT_immediate, rows.RAVLT_learning,rows.RAVLT_forgetting,
                                   rows.LDELTOTAL, rows.DIGITSCOR, rows.EcogPtTotal])
    else:
        revised_scores.append(['Not found']*12)

In [17]:
current_sheet[['Behavioural_EXAMDATE', 'APOE4_revised', 'ADAS11_revised', 'ADAS13_revised', 'MMSE_revised', 'CDRSB_revised',
               'RAVLT_immediate_revised', 'RAVLT_learning_revised', 'RAVLT_forgetting_revised',
               'LDELTOTAL_revised', 'DIGITSCOR_revised', 'EcogPtTotal_revised']] = pd.DataFrame(revised_scores,index=current_sheet.index)

In [18]:
current_sheet.head()

Subject ID  Sex  Weight  Research Group                        Visit   \
1  021_S_6312  M      81.7             CN           ADNI3 Year 1 Visit    
2  301_S_6326  M      73.0             CN               ADNI Screening    
3  301_S_6326  M      68.0             CN           ADNI3 Year 1 Visit    
4  002_S_4473  M      77.0           EMCI   ADNI2 Screening MRI-New Pt    
5  002_S_4473  M      75.0           EMCI     ADNI2 Month 3 MRI-New Pt    

  Study Date   Age                Description   \
1  2019-04-30  81.3  Axial rsfMRI (Eyes Open)    
2  2018-04-26  75.8   Axial fcMRI (EYES OPEN)    
3  2019-06-06  76.9   Axial fcMRI (EYES OPEN)    
4  2012-02-10  74.9        Resting State fMRI    
5  2012-05-17  75.2        Resting State fMRI    

                                   Imaging Protocol   \
1  Manufacturer=GE MEDICAL SYSTEMS;Field Strength...   
2  Manufacturer=Philips Medical Systems;Field Str...   
3  Manufacturer=Philips Medical Systems;Field Str...   
4  Manufacturer=Philips Medical Systems;Field Str...   
5  Manufacturer=Philips Medical Systems;Field Str...   

  Cohort Assigned (by script)  ... ADAS11_revised ADAS13_revised MMSE_revised  \
1                     MCI_NC   ...             10             16           26   
2                     MCI_NC   ...             10             15           29   
3                     MCI_NC   ...           9.67          13.67           29   
4                     MCI_NC   ...              7             11           27   
5                     MCI_NC   ...            NaN            NaN          NaN   

  CDRSB_revised RAVLT_immediate_revised RAVLT_learning_revised  \
1             0                      29                      0   
2             0                      32                      5   
3             1                      38                      3   
4             2                      44                      7   
5           NaN                     NaN                    NaN   

  RAVLT_forgetting_revised LDELTOTAL_revised DIGITSCOR_revised  \
1                        6                12               NaN   
2                        5                 9               NaN   
3                        5                 8               NaN   
4                        4                11               NaN   
5                      NaN               NaN               NaN   

  EcogPtTotal_revised  
1             1.37838  
2             1.18421  
3             1.28947  
4             1.84615  
5                 NaN  

[5 rows x 32 columns]

## Rearranging the columns

In [19]:
current_sheet.columns

Index(['Subject ID ', 'Sex', 'Weight ', 'Research Group ', 'Visit ',
       'Study Date ', 'Age ', 'Description ', 'Imaging Protocol ',
       'Cohort Assigned (by script)', 'ADAS 11', 'ADAS 13', 'MMSE', 'CDR_SB',
       'RAVLT_immediate', 'RAVLT_learning', 'RAVLT_forget', 'LDEL_Total',
       'Digit_SCore', 'ECog_Pt_Total', 'Behavioural_EXAMDATE', 'APOE4_revised',
       'ADAS11_revised', 'ADAS13_revised', 'MMSE_revised', 'CDRSB_revised',
       'RAVLT_immediate_revised', 'RAVLT_learning_revised',
       'RAVLT_forgetting_revised', 'LDELTOTAL_revised', 'DIGITSCOR_revised',
       'EcogPtTotal_revised'],
      dtype='object')

In [23]:
current_sheet.columns = ['Subject ID', 'Sex', 'Weight', 'Research Group', 'Visit',
       'Study Date', 'Age', 'Description', 'Imaging Protocol',
       'Cohort Assigned (by script)', 'ADAS 11', 'ADAS 13', 'MMSE', 'CDR_SB',
       'RAVLT_immediate', 'RAVLT_learning', 'RAVLT_forget', 'LDEL_Total',
       'Digit_SCore', 'ECog_Pt_Total', 'Behavioural_EXAMDATE', 'APOE4_revised',
       'ADAS11_revised', 'ADAS13_revised', 'MMSE_revised', 'CDRSB_revised',
       'RAVLT_immediate_revised', 'RAVLT_learning_revised',
       'RAVLT_forgetting_revised', 'LDELTOTAL_revised', 'DIGITSCOR_revised',
       'EcogPtTotal_revised']
current_sheet = current_sheet[['Subject ID', 'Sex', 'Weight', 'Research Group', 'Visit',
       'Age', 'Description', 'Imaging Protocol',
       'Cohort Assigned (by script)', 'ADAS 11', 'ADAS 13', 'MMSE', 'CDR_SB',
       'RAVLT_immediate', 'RAVLT_learning', 'RAVLT_forget', 'LDEL_Total',
       'Digit_SCore', 'ECog_Pt_Total', 'Study Date', 'Behavioural_EXAMDATE', 'APOE4_revised',
       'ADAS11_revised', 'ADAS13_revised', 'MMSE_revised', 'CDRSB_revised',
       'RAVLT_immediate_revised', 'RAVLT_learning_revised',
       'RAVLT_forgetting_revised', 'LDELTOTAL_revised', 'DIGITSCOR_revised',
       'EcogPtTotal_revised']]

# Checking if the scores repeated for any subject

In [39]:
check_df = current_sheet[['Subject ID', 'Behavioural_EXAMDATE']]
print(check_df.shape)
# check_df.drop_duplicates(inplace=True)
# print(check_df.shape)
print(current_sheet.duplicated().index)
print(check_df.duplicated().index)
print(len(current_sheet[current_sheet.duplicated()].index),len(check_df[check_df.duplicated()].index))
list(set(list(check_df[check_df.duplicated()].index)) - set(list(current_sheet[current_sheet.duplicated()].index)))

(1705, 2)
Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705],
           dtype='int64', length=1705)
Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705],
           dtype='int64', length=1705)
64 69


[864, 580, 1323, 1453, 1487]

In [37]:
pd.set_option('display.max_columns', 500)
current_sheet.loc[[863,864, 579,580, 1322,1323, 1452,1453, 1486,1487]]

Subject ID Sex  Weight Research Group                         Visit  \
863   130_S_4415  F     73.0          EMCI   ADNI3 Initial Visit-Cont Pt    
864   130_S_4415  F     73.0          EMCI   ADNI3 Initial Visit-Cont Pt    
579   037_S_4214  M     66.4          LMCI            ADNI3 Year 1 Visit    
580   037_S_4214  M     68.0          LMCI            ADNI3 Year 2 Visit    
1322  012_S_4643  F     68.0            CN            ADNI3 Year 1 Visit    
1323  012_S_4643  F     57.6            CN            ADNI3 Year 2 Visit    
1452  100_S_1286  F     60.0            CN            ADNI2 Year 2 Visit    
1453  100_S_1286  F    110.0            CN            ADNI2 Year 2 Visit    
1486  141_S_6008  F     65.8            CN            ADNI3 Year 1 Visit    
1487  141_S_6008  F     65.8            CN            ADNI3 Year 2 Visit    

       Age                      Description  \
863   81.0  Axial fcMRI (EYES OPEN)_REPEAT    
864   81.0         Axial fcMRI (EYES OPEN)    
579   81.3     Axial MB rsfMRI (Eyes Open)    
580   81.6     Axial MB rsfMRI (Eyes Open)    
1322  72.2        Axial rsfMRI (Eyes Open)    
1323  72.5        Axial rsfMRI (Eyes Open)    
1452  82.7     Extended Resting State fMRI    
1453  82.8     Extended Resting State fMRI    
1486  64.9        Axial rsfMRI (EYES OPEN)    
1487  65.3        Axial rsfMRI (EYES OPEN)    

                                       Imaging Protocol  \
863   Manufacturer=Philips Medical Systems;Field Str...   
864   Manufacturer=Philips Medical Systems;Field Str...   
579            Manufacturer=SIEMENS;Field Strength=3.0    
580            Manufacturer=SIEMENS;Field Strength=3.0    
1322           Manufacturer=SIEMENS;Field Strength=3.0    
1323           Manufacturer=SIEMENS;Field Strength=3.0    
1452  Manufacturer=Philips Medical Systems;Field Str...   
1453  Manufacturer=Philips Medical Systems;Field Str...   
1486           Manufacturer=SIEMENS;Field Strength=3.0    
1487           Manufacturer=SIEMENS;Field Strength=3.0    

     Cohort Assigned (by script) ADAS 11 ADAS 13 MMSE CDR_SB RAVLT_immediate  \
863                       MCI_C       24      33   25      8              25   
864                       MCI_C       24      33   25      8              25   
579                   MCI_multi       14      21   29      0              23   
580                   MCI_multi       []      []   []     []              []   
1322                         CN     6.67    9.67  NaN    NaN              63   
1323                         CN       []      []   []     []              []   
1452                         CN       []      []   []     []              []   
1453                         CN       []      []   []     []              []   
1486                         CN      NaN     NaN   29      0              41   
1487                         CN       []      []   []     []              []   

     RAVLT_learning RAVLT_forget LDEL_Total Digit_SCore ECog_Pt_Total  \
863               0            3          0         NaN             1   
864               0            3          0         NaN             1   
579               1            5          7         NaN       1.31579   
580              []           []         []          []            []   
1322              6            2         16         NaN       1.21053   
1323             []           []         []          []            []   
1452             []           []         []          []            []   
1453             []           []         []          []            []   
1486              7            1         14         NaN       1.02703   
1487             []           []         []          []            []   

     Study Date Behavioural_EXAMDATE APOE4_revised ADAS11_revised  \
863  2017-10-03  2017-09-26 00:00:00             2             24   
864  2017-10-03  2017-09-26 00:00:00             2             24   
579  2018-09-26  2018-09-26 00:00:00             0             14   
580  2019-01-30  2018-09-26 0

index 863,864 correspond to same scan date just that one of the fmri has 'repeat' in its name, so we can ignore it.<br>
For index 580, 1323, 1453, 1487 it seems no behavioural test was performed close to scan date, and hence the scores of the behavioural test for previous scan date are coming in the dataframe, as they are within 150 days range<br>
For these four rows I plan to change the revised scores to Not float('nan').

In [60]:
current_sheet.loc[[580, 1323, 1453, 1487],['Behavioural_EXAMDATE', 'APOE4_revised',
       'ADAS11_revised', 'ADAS13_revised', 'MMSE_revised', 'CDRSB_revised',
       'RAVLT_immediate_revised', 'RAVLT_learning_revised',
       'RAVLT_forgetting_revised', 'LDELTOTAL_revised', 'DIGITSCOR_revised',
       'EcogPtTotal_revised']] = [[float('nan')]*12]*4

In [61]:
current_sheet.loc[[580, 1323, 1453, 1487],['Behavioural_EXAMDATE', 'APOE4_revised',
       'ADAS11_revised', 'ADAS13_revised', 'MMSE_revised', 'CDRSB_revised',
       'RAVLT_immediate_revised', 'RAVLT_learning_revised',
       'RAVLT_forgetting_revised', 'LDELTOTAL_revised', 'DIGITSCOR_revised',
       'EcogPtTotal_revised']]

Behavioural_EXAMDATE APOE4_revised ADAS11_revised ADAS13_revised  \
580                   NaN           NaN            NaN            NaN   
1323                  NaN           NaN            NaN            NaN   
1453                  NaN           NaN            NaN            NaN   
1487                  NaN           NaN            NaN            NaN   

     MMSE_revised CDRSB_revised RAVLT_immediate_revised  \
580           NaN           NaN                     NaN   
1323          NaN           NaN                     NaN   
1453          NaN           NaN                     NaN   
1487          NaN           NaN                     NaN   

     RAVLT_learning_revised RAVLT_forgetting_revised LDELTOTAL_revised  \
580                     NaN                      NaN               NaN   
1323                    NaN                      NaN               NaN   
1453                    NaN                      NaN               NaN   
1487                    NaN                      NaN               NaN   

     DIGITSCOR_revised EcogPtTotal_revised  
580                NaN                 NaN  
1323               NaN                 NaN  
1453               NaN                 NaN  
1487               NaN                 NaN

# Let's check if we are done

In [62]:
check_df = current_sheet[['Subject ID', 'Behavioural_EXAMDATE']]
print(check_df.shape)
# check_df.drop_duplicates(inplace=True)
# print(check_df.shape)
print(current_sheet.duplicated().index)
print(check_df.duplicated().index)
print(len(current_sheet[current_sheet.duplicated()].index),len(check_df[check_df.duplicated()].index))
list(set(list(check_df[check_df.duplicated()].index)) - set(list(current_sheet[current_sheet.duplicated()].index)))

(1705, 2)
Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705],
           dtype='int64', length=1705)
Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705],
           dtype='int64', length=1705)
64 65


[864]

# Seems we are done

In [63]:
print(current_sheet.shape)

(1705, 32)


In [64]:
current_sheet.to_csv('revised_scores_sheet.csv')